#fundmental concepts of tensor flow

#introduction to tensors

In [1]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
#create tensors with tf.constant
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#chwwck the number of dimensions(ndim)
scalar.ndim


0

In [4]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the vector dimension
vector.ndim

1

In [6]:
#create a matrix more than 1 dimension
matrix=tf.constant([[10,7],[22,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [22, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
m2=tf.constant([[10.,7.],[3.,2.],[8.,9.]])
m2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [9]:
m3=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)
m3

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
m3.ndim

2

In [11]:
m2.ndim

2

In [12]:
#lets create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

#tensor with tf variable

In [14]:
#create the tensor with th.variable


In [15]:
c=tf.Variable([10,7])
d=tf.constant([10,7])
c


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [16]:
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [17]:
#lets try chang elemnt in c tensor
c[0].assign(7)
c

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [60]:
#lets try change elemnet in d tensor(unchangable sensor)
d[0].assign(9)
d

AttributeError: ignored

#create random sensors

In [ ]:
#create random tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

In [ ]:
random_2=tf.random.Generator.from_seed(41)
random_2=random_2.normal(shape=(3,2))
random_2

##shuffle the order of elements in a tensor

In [ ]:
#shuffle a tensor(valuable for when you want shuffle data)
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
#shuffle our non shuffle tensor
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

In [ ]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled,seed=42) #operation level random seed

##other wise to make tensors


In [ ]:
#tensor of all ones
tf.ones([3,4])


In [ ]:
#You can also turn numpy arrays into tensors

#The main difference between numpy arrays and tensor flow tensors is that tensors can be run on a GPU(much faster for numerical computing)

In [ ]:
import numpy as np
numpy_a=np.arange(1,25, dtype=np.int16)
numpy_a

In [ ]:
A=tf.constant(numpy_a,shape=(2,3,4))
A

In [ ]:
B=tf.constant(numpy_a)
B

In [ ]:
#2*3*4=24

#getting information from tensor
*shape
*rank
*axis or dimension
*size

In [ ]:
#create a rank 4 tensor
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

In [ ]:
#get various attributes of our tensor'
print("datatypes of every element:",rank_4_tensor.dtype)
print("Number of dimensions(rank):",rank_4_tensor.ndim)
print("shape of tensor:",rank_4_tensor.shape)
print("element along the 0 axis:",rank_4_tensor.shape[0])
print("element along the last axis:",rank_4_tensor.shape[-1])
print("total number of elements in our tensor:",tf.size(rank_4_tensor))
print("total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

#indexing tensors


#tensors can be indexted just like python lists

In [ ]:
some_list=[1,2,3,4]
some_list[:2]

In [ ]:
#get the first element of each dimension
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
#get the first element from each dimension from each index except for the first one
rank_4_tensor[:1,:1,:1,]

In [ ]:
#create a rank 2 tensor(2 dimensions)
rank_2_tensor=tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

In [ ]:
some_list,some_list[-1]

In [ ]:
from tensorflow.python.ops.gen_array_ops import rank
#get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

In [43]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
#add in extra dimensions to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [45]:
#alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)# -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [46]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [47]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

#manipulating tensor

#basic operatios

In [48]:
#addition
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [49]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [50]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

#matrix multiplication

In [51]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
#matrix multiplication with python opeartior @

In [54]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [55]:
tensor.shape

TensorShape([2, 2])

In [ ]:
#create  a tensor(3,2) tensor

In [ ]:
x=tf.constant([[1,2],[3,4],[5,6]])
#create anothe (3,2)
y=tf.constant([[7,8],[9,10],[11,12]])

In [58]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [103]:
#tey metrix mutiplication
x @ y

InvalidArgumentError: ignored

In [104]:
#let"s change shape of y
z=tf.reshape(y,shape=(2,3))

In [105]:
x @ z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [106]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

#changing the datatyoe of a tensor

In [107]:
b=tf.constant([1.7,7.4])
b.dtype

tf.float32

In [108]:
c=tf.constant([7,10])
c.dtype

tf.int32

In [109]:
#change float 32 to float 16
c=tf.constant([7,10],dtype=np.float16)
c.dtype

tf.float16

In [110]:
d=tf.cast(b,dtype=tf.float16)
d,d.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

#aggregating tensor

In [111]:
#get the absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [112]:
#get absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [113]:
#lets go through the following form of aggregation
#get the minimum
#get maximum
#get mean
#get the sum of the tensor


In [114]:
#create a  randomo tensor with 0 and 100 of size 50
e=tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([78, 87,  4, 52,  7,  9, 84, 59,  8, 62, 85, 17, 28, 55, 96,  2, 52,
       92, 33, 55, 34, 71, 23, 33, 90, 44, 75, 93, 60,  7, 51, 18, 73, 76,
       31, 45, 80, 95, 72, 66, 89, 83, 12, 48, 37, 38, 84, 28, 90, 84])>

In [115]:
tf.size(e),e.shape,e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [116]:
#find the minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [117]:
#find the maximum
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [118]:
#find the avarge
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [119]:
#find the sum 
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2695>

In [120]:
#find the standard deveaion


In [121]:
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=847>

In [122]:
#find the standard deviation
tf.math.reduce_std(tf.cast(e,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.097939>

In [123]:
#find the position maximum and minimum of a tensor

In [124]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [125]:
#find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [126]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [127]:
#find the_max(F)
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [128]:
#check for equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [129]:
#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [130]:
#find the minimm using the positional minimun index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

#SQUEEZING A TENSOR

In [131]:
#removing all single dimensional
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [132]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [133]:
g_squeezed=tf.squeeze(G)
g_squeezed,g_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

#one hot encoding


In [134]:
some_list=[0,1,2,3]#could be red,green,blue
#one hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [135]:
#specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="yo I love deep learning",off_value="i like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'i like to dance',
        b'i like to dance', b'i like to dance'],
       [b'i like to dance', b'yo I love deep learning',
        b'i like to dance', b'i like to dance'],
       [b'i like to dance', b'i like to dance',
        b'yo I love deep learning', b'i like to dance'],
       [b'i like to dance', b'i like to dance', b'i like to dance',
        b'yo I love deep learning']], dtype=object)>

In [136]:
#squaring,log,squre root

In [137]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [138]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [139]:
tf.sqrt(tf.cast(H, dtype=tf.float32 ))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [140]:
#find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

##tensors and NUmpy

In [141]:
#create a tensor directly from a numpy
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [142]:
#Convert tensor J to a Numpy array

In [143]:
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

#finding acess to GPU



In [2]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Thu Aug  4 00:06:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------